export const ROLES = Object.freeze({
  SUPER_ADMIN: "SuperAdmin",
  ADMINISTRATOR: "Administrator",
  STANDARD_USER: "Standard",
});

export type PermissionMatrix = { [key: string]: string[] };

export const PERMISSIONS: PermissionMatrix = Object.freeze({
  CAN_DELETE: [ROLES.SUPER_ADMIN],
  CAN_CREATE: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRATOR],
  CAN_UPDATE: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRATOR],
  PUBLIC_ACCESS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRATOR, ROLES.STANDARD_USER],
  PRIVATE_ACCESS: [ROLES.SUPER_ADMIN, ROLES.ADMINISTRATOR],
});

export const PERMISSION_LABELS = Object.freeze({
  CAN_DELETE: "CAN_DELETE",
  CAN_CREATE: "CAN_CREATE",
  CAN_UPDATE: "CAN_UPDATE",
  PUBLIC_ACCESS: "PUBLIC_ACCESS",
  PRIVATE_ACCESS: "PRIVATE_ACCESS",
});
